sorintlab/sircles

.travis.yml, scripts/test.sh
Make travis tests work also with forked repos so users can run their
travis tests before opening a PR.
Do also the full build instead of only running tests.
Execute standardjs linting of the ui.
=> travis: improve tests

.travis.yml, Makefile
Use travis ".x" versioning to pull latest minor version.
Update dockerhub golang image to golang:1.9
=> build: update to golang 1.9

api/graphql/schema.go
If the avatar image isn't provided in the create/update member mutation the
current code will panic since we are type asserting a nil value.
Move type assertion after checking that avatar isn't nil.
=> graphql: handle missing avatar image

api/graphql/role.go, api/graphql/schema_test.go, models/accountability.go, models/domain.go, models/role.go
sort roles, accountabilities and domains by name to make them reproducible also
on postgres. It wasn't an issue with sqlite3 because they are returned in the
insert order.
This is needed to run tests using postgres instead of sqlite3.
=> graphql: reproducible roles, accountabilities, domains order

api/graphql/schema_test.go
If the provided string is empty generate a random UUID instead of the same UUID.
Remove unused global uuid counter
=> tests: fix uuid generation

api/graphql/member.go, api/graphql/role.go, api/graphql/schema.go, api/graphql/schema_test.go, api/graphql/tension.go, api/graphql/timeline.go, auth/auth.go, cmd/sircles/server.go, command/command.go, command/commands/commands.go, common/timegenerator.go, dataloader/dataloader.go, db/migration.go, eventstore/event.go, eventstore/eventstore.go, handlers/auth.go, handlers/avatar.go, handlers/graphql.go, models/roleevent.go, readdb/readdb.go, search/search.go, util/graphql.go, web/src/app/containers/TimeTravel.js, web/src/app/containers/TimeTravelMessage.js
Remove the generation of a serialized timeline and related timeline "aggregate"
that is one of the reasons why we currently have all the commands serialized.
Instead, detect every new timeline using the event groupID, every group of
events triggered by a commands will have a different groupID, we are not using
the correlationID since multiple commands could be correlated and have the same
correlationID, we are not using the causationID because multiple commands may be
triggered by the same event and so have the same causationID. The timeline
timestamp is the timestamp of the first event in that groupID.
The TimeLineNumber that is replacing the TimeLineSequenceNumber is dinamically
generated from the timeline timestamp converted to unixnano.
=> *: Remove serialized timeline generation

api/graphql/schema.go, db/migration.go, readdb/readdb.go
Save for every timeline the related aggregate type and id and improve TimeLines
method to filter by them if provided.
=> readdb: handle aggregate type and id in timeline

api/graphql/schema_test.go, cmd/sircles/dump.go, cmd/sircles/restore.go, cmd/sircles/server.go, db/db.go, db/migration.go, eventstore/eventstore_test.go
in future the migrate function will be split and moved to its related db (eventstore,
readdb etc...)
This change is needed to be able to reuse the db methods also for local
aggregate snapshot/caches.
=> db: call migrate outside NewDB

api/graphql/schema.go, api/graphql/search.go, auth/ldap.go, cmd/sircles/dump.go, cmd/sircles/restore.go, cmd/sircles/server.go, config/config.go, db/db.go, eventstore/eventstore.go, handlers/auth.go, handlers/graphql.go, readdb/readdb.go, search/search.go, util/graphql.go
Try to provide a proper stack trace without adding redundant stack traces. For
how pkg/errors works this is currently a manual and error prone work. The rules
are these:
* Use errors.New/Errorf when creating a new error, this will save a stacktrace
* Use errors.Wrap/Wrapf/WithStack when calling an external library that doens't return an
error with a stacktrace
* Just return the errors or use errors.WithMessage when returning an error
generated inside the app or a library that returns an error that already have
a stacktrace
* For errors returned with a channel by another go routine it's useful to record
also another stacktrace using errors.Wrap/Wrapf/WithStack.
Also use #+v when logging errors to also print the stacktrace (we aren't
currently using zap as a structured logger, in that case …
=> *: improve error handling

command/command.go, db/migration.go, eventstore/event.go, eventstore/eventstore.go, eventstore/eventstore_test.go, readdb/readdb.go, search/search.go, util/id.go
In future we'll need aggregateid in other forms than uuid (i.e. string names).
=> eventstore: make AggregateID a string

api/graphql/schema_test.go, cmd/sircles/restore.go, command/command.go, db/db.go, db/migration.go, eventstore/eventstore.go, eventstore/eventstore_test.go, readdb/readdb.go
The eventstore now accepts concurrent writes. They are currently masked by the
serializable isolation level due to the current architecture of a single tx for
every command shared also with the readdb.
This will be relaxed in future when moving to a completely decoupled eventstore
and readdb.
The WriteEvents method requires that all the events are for the same aggregate
and will check that the provided current aggregate version is the current one in
the store to check concurrent writes to the same aggregate.
Since in future there can be many concurrent transactions the above check won't
work with concurrent transactions but it's enforced by an unique constraint on
the aggregate event version that will make the transaction fail.
The global sequence number is now provided by a sequence so …
=> eventstore: initial concurrent writes implementation

api/graphql/member.go, api/graphql/role.go, api/graphql/roleevent.go, api/graphql/schema.go, api/graphql/schema_test.go, api/graphql/search.go, api/graphql/tension.go, api/graphql/timeline.go, auth/auth.go, auth/local.go, cmd/sircles/restore.go, cmd/sircles/server.go, command/command.go, dataloader/dataloader.go, handlers/auth.go, handlers/avatar.go, handlers/graphql.go, readdb/readdb.go, search/search.go
* Remove Internal methods
* Use context in all functions
* Rename ReadDB interface to ReadDBService
* Rename DBService to readDBService and make it unexported
=> readdb: remove Internal methods and always use context

search/search.go
This will happen when the readdb is empty
=> search: skip indexing when curtimeline is empty

api/graphql/schema.go, api/graphql/schema_test.go, api/graphql/timeline.go, util/graphql.go
We have int64 timelines but javascript cannot handle 64 bit number without using
external libraries. The effect is that we lose the nanosecond part. So we
marshal it into a string.
=> util: marshal timeline into a string to not lose time precision

command/command.go, command/commands/commands.go
Since it's a command triggering events put causationID and correlationID inside
it so they can be used by the aggregate to populate events.
It'll be needed for future real aggregates implementations.
=> commands: propagate correlationID and causationID

glide.lock, scripts/glide-update.sh, vendor/github.com/mattn/go-sqlite3/sqlite3-binding.h, vendor/github.com/mattn/go-sqlite3/sqlite3ext.h, vendor/go.uber.org/atomic/string.go
They are based on sqlite 3.17.0 and now there's sqlite 3.21.0 which looks to be
better handle concurrent writes with its busy handler and the tests are two
times faster.
=> vendor: update sqlite provided bindings

eventstore/eventstore.go
GetEvents uses a count handling assuming that sequence numbers are
gapless. Now they aren't gapless so change it to use limit instead of a range.
=> eventstore: fix GetEvents count handling

cmd/sircles/restore.go, command/command.go, command/commands/commands.go, db/migration.go, eventstore/event.go, eventstore/eventstore.go, eventstore/eventstore_test.go, readdb/readdb.go, search/search.go
* Split between the event generated and the event stored structures
* The correlationID, causationID, groupID are not part of the stored event but
are moved to the event metadata.
* The eventstore won't marshall/unmarshall the event data and metadata
* The generated event struct contains only the eventtype, the event data and the
event metadata
* The correlationID, causationID, groupID are the same for all the aggregate
events generated by that command invocation.
=> eventstore: various improvements and simplifications

api/graphql/schema_test.go, command/command.go, command/commands/commands.go, eventstore/event.go, eventstore/eventstore_test.go, models/roleevent.go, readdb/readdb.go, search/search.go
do not use events to save commands. They aren't an aggregate event.
In future add a way to log them for auditing and correlation with generated
events.
The command's IssuerID is moved to every event metadata as CommandIssuerID since
it's needed by the readdb.
=> *: remove command events

listennotify/listennotify.go, listennotify/local.go, listennotify/postgres.go
This commit adds a package to handle notifications.
They'll be used by the eventstore and the readdb to notify new changes.
Two kind of listener/notify are implemented: a local one and a postgres based
one.
=> Add listen notify package

api/graphql/schema_test.go, cmd/sircles/dump.go, command/command.go, db/migration.go, eventstore/event.go, eventstore/eventstore.go, eventstore/eventstore_test.go, readdb/readdb.go, search/search.go
Remove references to aggregate. Every aggregate events will be saved in a
stream. The aggregateType becomes a category.
=> eventstore: remove aggregate references.
